name: Deploy app to cluster

on:
  workflow_dispatch:
  push:
    branches:
      - feature/workflow
    paths:
      - 'python-chart/**'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 3.18.4

      - name: Helm lint
        run: helm lint
        working-directory: ./python-chart

      - name: Set Kubeconfig Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Helm chart
        run: helm upgrade --install python-chart ./python-chart

