name: Deploy app to cluster

on:
  workflow_dispatch:
  push:
    branches:
      - feature/workflow
    paths:
      - 'python-chart/**'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 3.18.4

      - name: Download kubeconfig
        run: |
          echo "${KUBE_CONFIG}" > ~/kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Helm lint
        run: helm lint
        working-directory: ./python-chart

      - name: Cat kubeconfig
        run: cat ~/kubeconfig

      - name: Deploy Helm chart
        run: export KUBECONFIG=./kubeconfig && helm upgrade --install python-chart ./python-chart

